language: node_js
node_js:
  - "10"
sudo: required
services:
- docker

before_install:
  - export REDIS_HOST=$REDIS_HOST
  - export SERVER_PORT=$SERVER_PORT
  - export SERVER_PORT=$REDIS_CLIENT_URL
  - docker-compose up -d
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: "helios-email"
  skip_cleanup: true
  env: "HeliosEmail-env"
  bucket_name: "elasticbeanstalk-us-west-1-154847616911"
  bucket_path: "helios-email-service"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

after_deploy:
  - echo "done deploying"